services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
      - ml-service

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4005:4000"
    environment:
      - APP_PORT=4000
      - FRONTEND_URL=http://localhost:5173

  ml-service:
    build:
      context: ./apps/ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
