import React, { useState, useEffect } from 'react';
import { useErp } from '../context/ErpContext';
import { Shield, Key, RefreshCw, Cpu, Award, CheckCircle, Trash2, UserPlus, Users, Mail, Building } from 'lucide-react';

export const AuthManager: React.FC = () => {
  const { activeTenant, logApiCall, usersList, adminCreateUser, adminDeleteUser } = useErp();
  const [totp, setTotp] = useState('');
  const [enteredTotp, setEnteredTotp] = useState('');
  const [mfaVerified, setMfaVerified] = useState(false);
  const [jwt, setJwt] = useState('');
  const [decodedJwt, setDecodedJwt] = useState<any>(null);

  // User creation form states
  const [newUserName, setNewUserName] = useState('');
  const [newUserEmail, setNewUserEmail] = useState('');
  const [newUserPassword, setNewUserPassword] = useState('');
  const [newUserTenant, setNewUserTenant] = useState('t-amdox');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Generate a random mock TOTP every 30s
  useEffect(() => {
    const generateTotp = () => {
      const code = Math.floor(100000 + Math.random() * 900000).toString();
      setTotp(code);
    };
    generateTotp();
    const interval = setInterval(generateTotp, 30000);
    return () => clearInterval(interval);
  }, []);

  // Update JWT based on Tenant Context
  useEffect(() => {
    const header = { alg: 'RS256', typ: 'JWT', kid: 'key-amdox-2026-v1' };
    const payload = {
      iss: `https://auth.amdox.io/realms/${activeTenant.id}`,
      sub: 'usr_8f1a2692bc80',
      aud: 'amdox-erp-client',
      exp: Math.floor(Date.now() / 1000) + 3600,
      iat: Math.floor(Date.now() / 1000),
      tenant_id: activeTenant.id,
      tenant_domain: activeTenant.domain,
      roles: ['SuperAdmin', 'FinanceManager', 'ProcurementLead'],
      mfa_verified: mfaVerified,
      identity_provider: activeTenant.provider
    };
    const signature = 'k_R2390a-Z2f_891eFJKW9A7B6C5D4e3f2g1h0i_j81K';
    const mockJwt = `${btoa(JSON.stringify(header))}.${btoa(JSON.stringify(payload))}.${signature}`;
    setJwt(mockJwt);
    setDecodedJwt({ header, payload });
  }, [activeTenant, mfaVerified]);

  const verifyMfa = () => {
    const start = performance.now();
    if (enteredTotp === totp) {
      setMfaVerified(true);
      logApiCall('POST', '/api/v1/auth/mfa/verify', 200, Math.round(performance.now() - start));
    } else {
      alert('Invalid MFA Token. Check current token shown below.');
      logApiCall('POST', '/api/v1/auth/mfa/verify', 401, Math.round(performance.now() - start));
    }
  };

  return (
    <div className="space-y-6 animate-slide-up">
      {/* Overview */}
      <div className="glass-card p-6 rounded-2xl">
        <h2 className="text-2xl font-display font-bold text-slate-100 flex items-center gap-3">
          <Shield className="w-6 h-6 text-purple-400" /> Identity & Access Management (F-01)
        </h2>
        <p className="text-slate-400 mt-2 text-sm leading-relaxed">
          AMX-ERP integrates with enterprise identity providers via SAML 2.0 and OIDC (OAuth 2.0). 
          Tenants are securely isolated using standard web tokens and cryptographically signed keys.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* MFA Simulator */}
        <div className="glass-card p-6 rounded-2xl flex flex-col justify-between">
          <div>
            <h3 className="text-lg font-display font-semibold text-slate-200 flex items-center gap-2 mb-4">
              <Key className="w-5 h-5 text-emerald-400" /> Multi-Factor Authentication
            </h3>
            
            {mfaVerified ? (
              <div className="bg-emerald-500/10 border border-emerald-500/20 p-6 rounded-xl text-center space-y-3">
                <CheckCircle className="w-12 h-12 text-emerald-400 mx-auto" />
                <h4 className="text-emerald-300 font-medium">MFA Verification Passed</h4>
                <p className="text-xs text-slate-400">Your session is authenticated with Level-3 Assurance (AAL3).</p>
                <button 
                  onClick={() => setMfaVerified(false)}
                  className="mt-4 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg transition"
                >
                  Reset MFA Session
                </button>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-xs text-slate-400 leading-relaxed">
                  Enter the 6-digit verification code generated by your Authenticator App.
                </p>
                
                <div className="flex items-center gap-3">
                  <input 
                    type="text" 
                    placeholder="e.g. 123456" 
                    value={enteredTotp}
                    onChange={(e) => setEnteredTotp(e.target.value)}
                    maxLength={6}
                    className="bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-center tracking-widest text-lg font-mono text-slate-100 focus:outline-none focus:border-purple-500 flex-1"
                  />
                  <button 
                    onClick={verifyMfa}
                    className="bg-purple-600 hover:bg-purple-500 text-slate-100 font-semibold px-6 py-3 rounded-xl text-sm transition"
                  >
                    Verify
                  </button>
                </div>

                <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-800/80 flex justify-between items-center">
                  <div>
                    <span className="text-xs text-slate-500 block uppercase font-semibold">Active MFA Token (Mock Device)</span>
                    <span className="text-xl font-mono text-purple-400 font-bold tracking-wider">{totp}</span>
                  </div>
                  <div className="text-right">
                    <span className="text-xs text-slate-500 block">Rotate Duration</span>
                    <span className="text-xs text-slate-400 flex items-center gap-1"><RefreshCw className="w-3 h-3 animate-spin-slow" /> 30 Seconds</span>
                  </div>
                </div>
              </div>
            )}
          </div>
          
          <div className="mt-6 border-t border-slate-800 pt-4 flex justify-between items-center text-xs text-slate-500">
            <span>Identity Provider: {activeTenant.provider}</span>
            <span>Uptime SLA: 99.99%</span>
          </div>
        </div>

        {/* Token Decoder */}
        <div className="glass-card p-6 rounded-2xl flex flex-col justify-between">
          <div>
            <h3 className="text-lg font-display font-semibold text-slate-200 flex items-center gap-2 mb-4">
              <Cpu className="w-5 h-5 text-amber-400" /> Active JWT RS256 Token
            </h3>
            
            <div className="space-y-4">
              <div>
                <span className="text-xs text-slate-500 block mb-1">Raw Base64 Encoded Token</span>
                <div className="bg-slate-950 p-3 rounded-xl font-mono text-[10px] text-purple-300 break-all border border-slate-850 h-24 overflow-y-auto">
                  {jwt}
                </div>
              </div>

              {decodedJwt && (
                <div>
                  <span className="text-xs text-slate-500 block mb-1">Parsed Token Claims</span>
                  <div className="grid grid-cols-2 gap-2 text-xs font-mono">
                    <div className="bg-slate-900/60 p-2.5 rounded-lg border border-slate-800">
                      <span className="text-[10px] text-slate-500 block">Issuer (iss)</span>
                      <span className="text-slate-300 truncate block">{decodedJwt.payload.iss}</span>
                    </div>
                    <div className="bg-slate-900/60 p-2.5 rounded-lg border border-slate-800">
                      <span className="text-[10px] text-slate-500 block">Subject (sub)</span>
                      <span className="text-slate-300 block">{decodedJwt.payload.sub}</span>
                    </div>
                    <div className="bg-slate-900/60 p-2.5 rounded-lg border border-slate-800">
                      <span className="text-[10px] text-slate-500 block">Tenant ID</span>
                      <span className="text-slate-300 block">{decodedJwt.payload.tenant_id}</span>
                    </div>
                    <div className="bg-slate-900/60 p-2.5 rounded-lg border border-slate-800">
                      <span className="text-[10px] text-slate-500 block">MFA Checked</span>
                      <span className={decodedJwt.payload.mfa_verified ? "text-emerald-400 font-bold block" : "text-amber-400 block"}>
                        {decodedJwt.payload.mfa_verified ? "TRUE" : "FALSE"}
                      </span>
                    </div>
                    <div className="bg-slate-900/60 p-2.5 rounded-lg border border-slate-800 col-span-2">
                      <span className="text-[10px] text-slate-500 block">Assigned Roles</span>
                      <span className="text-slate-300 block">{decodedJwt.payload.roles.join(', ')}</span>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
          
          <div className="mt-6 border-t border-slate-800 pt-4 text-xs text-slate-500 flex justify-between">
            <span className="flex items-center gap-1"><Award className="w-3.5 h-3.5 text-purple-400" /> OAuth Client: erp-api</span>
            <span>Algorithm: RS256</span>
          </div>
        </div>
      </div>

      {/* User Account Management Console */}
      <div className="glass-card p-6 rounded-2xl">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
          <div>
            <h3 className="text-lg font-display font-semibold text-slate-200 flex items-center gap-2">
              <Users className="w-5 h-5 text-purple-400" /> User Account Management Console
            </h3>
            <p className="text-xs text-slate-500 mt-1 font-sans">Manage active enterprise users, provision new credentials, or revoke tenant authorization.</p>
          </div>
          <span className="text-xs font-semibold px-3 py-1 bg-slate-900 border border-slate-800 rounded-full text-slate-400 font-mono flex items-center gap-1.5">
            Total Users: {usersList.length}
          </span>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
          {/* Create User Form */}
          <div className="bg-slate-950/40 p-5 rounded-2xl border border-slate-900 flex flex-col justify-between space-y-4 col-span-1">
            <h4 className="text-sm font-semibold text-slate-300 flex items-center gap-1.5 font-display">
              <UserPlus className="w-4 h-4 text-purple-400" /> Provision New User
            </h4>
            
            <form onSubmit={async (e) => {
              e.preventDefault();
              setIsSubmitting(true);
              const success = await adminCreateUser(newUserName, newUserEmail, newUserPassword, newUserTenant);
              setIsSubmitting(false);
              if (success) {
                setNewUserName('');
                setNewUserEmail('');
                setNewUserPassword('');
              }
            }} className="space-y-3.5">
              <div>
                <label className="text-[10px] text-slate-500 block uppercase font-bold mb-1">Full Name</label>
                <input 
                  type="text" 
                  value={newUserName}
                  onChange={(e) => setNewUserName(e.target.value)}
                  placeholder="e.g. Aryan Solanki"
                  required
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-xs text-slate-100 focus:outline-none focus:border-purple-500"
                />
              </div>

              <div>
                <label className="text-[10px] text-slate-500 block uppercase font-bold mb-1">Email Address</label>
                <input 
                  type="email" 
                  value={newUserEmail}
                  onChange={(e) => setNewUserEmail(e.target.value)}
                  placeholder="e.g. aryan@amdox.io"
                  required
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-xs text-slate-100 focus:outline-none focus:border-purple-500"
                />
              </div>

              <div>
                <label className="text-[10px] text-slate-500 block uppercase font-bold mb-1">Temporary Password</label>
                <input 
                  type="password" 
                  value={newUserPassword}
                  onChange={(e) => setNewUserPassword(e.target.value)}
                  placeholder="Minimum 6 characters"
                  required
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-xs text-slate-100 focus:outline-none focus:border-purple-500"
                />
              </div>

              <div>
                <label className="text-[10px] text-slate-500 block uppercase font-bold mb-1">Tenant Authority</label>
                <select
                  value={newUserTenant}
                  onChange={(e) => setNewUserTenant(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2.5 text-xs text-slate-350 focus:outline-none"
                >
                  <option value="t-amdox">Amdox Technologies (t-amdox)</option>
                  <option value="t-apex">Apex Logistics Inc. (t-apex)</option>
                  <option value="t-google">Global Retail Corp (t-google)</option>
                </select>
              </div>

              <button 
                type="submit"
                disabled={isSubmitting}
                className="w-full bg-purple-600 hover:bg-purple-500 disabled:bg-purple-800/40 text-slate-100 font-semibold py-2.5 rounded-xl text-xs transition flex items-center justify-center gap-2 mt-4"
              >
                <UserPlus className="w-3.5 h-3.5" /> {isSubmitting ? 'Provisioning...' : 'Provision Account'}
              </button>
            </form>
          </div>

          {/* User List Table */}
          <div className="xl:col-span-2">
            <div className="overflow-x-auto max-h-[380px] overflow-y-auto border border-slate-900 rounded-2xl bg-slate-950/20">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="border-b border-slate-900 text-slate-500 uppercase tracking-wider font-bold bg-slate-950/50">
                    <th className="p-3">User Details</th>
                    <th className="p-3">Email Address</th>
                    <th className="p-3">Tenant Domain</th>
                    <th className="p-3 text-center">Revoke Access</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-900">
                  {usersList.length > 0 ? (
                    usersList.map((usr) => (
                      <tr key={usr.email} className="hover:bg-slate-900/20 transition-all">
                        <td className="p-3 flex items-center gap-2.5">
                          <div className="w-7 h-7 rounded-full bg-purple-600/10 border border-purple-500/25 flex items-center justify-center text-[10px] font-bold text-purple-300 shrink-0">
                            {usr.name.split(' ').map(n => n[0]).join('')}
                          </div>
                          <div>
                            <span className="text-slate-200 block font-semibold">{usr.name}</span>
                            <span className="text-[9px] text-slate-500 block uppercase font-mono">Real-time DB</span>
                          </div>
                        </td>
                        <td className="p-3">
                          <div className="flex items-center gap-1.5 text-slate-350 font-mono text-[11px]">
                            <Mail className="w-3.5 h-3.5 text-slate-500" />
                            {usr.email}
                          </div>
                        </td>
                        <td className="p-3">
                          <span className="px-2 py-0.5 rounded text-[10px] bg-slate-900 border border-slate-800 text-slate-300 font-mono inline-flex items-center gap-1">
                            <Building className="w-3 h-3 text-purple-400" />
                            {usr.tenantId}
                          </span>
                        </td>
                        <td className="p-3 text-center">
                          <button
                            onClick={async () => {
                              if (confirm(`Are you sure you want to delete user ${usr.name} (${usr.email})?`)) {
                                await adminDeleteUser(usr.email);
                              }
                            }}
                            className="p-2 hover:bg-rose-500/10 border border-transparent hover:border-rose-500/20 rounded-xl text-slate-500 hover:text-rose-450 transition"
                            title="Delete User"
                          >
                            <Trash2 className="w-4 h-4 mx-auto" />
                          </button>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={4} className="py-6 text-center text-slate-500 italic">No users found. Reloading...</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
